name: test-demo
on:
 workflow_run:
    workflows: 
    - build-demo
    types:
    - completed
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: test stage
      run: echo "Test stage"