name: actions demo
on:
 push:
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v7
    - name: print index.html
      run: cat index.html
