name: Build-demo
run-name: This was triggered by @${{ github.actor }}
on:
 push:
    branches:
      - develop
jobs:
  build-job:
    env:
      APP_NAME: "Demo-app" 
    runs-on: ubuntu-latest 
    steps:
    - name: build stage
      run: echo "Build stage completed with ${APP_NAME}"  