name: Hello world        # Name of the work flow  
on:                      # Triggers when this workflow should trigger
 workflow_dispatch       # workflow_dispatch trigger used for manual trigger
jobs:
  hello-world:          # name of the job
    runs-on: ubuntu-latest
    steps:
    - name: hello-step
      run: |
        echo " hello shiva"
        echo "hello venshika"
      
