name: deploy-demo
run-name: This was triggered by @${{ github.actor }}
on:
  workflow_run:
    workflows:
    - test-demo
    types:
    - completed
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
    - name: deploy stage
      run: echo "Deploy stage"    