name: docker test
on:
  workflow_call:
    secrets:
      DOCKER_PASSWORD:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      imagetag: ${{ steps.tag1.outputs.ImageTag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3 

    - name: docker login
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}   

    - name: Build Image
      run: docker build -t businessnext-app .

    - name: Tag image
      run: docker tag businessnext-app sivatejanaidu78/businessnext-app:${{ steps.tag1.outputs.ImageTag }}

    - name: push images
      run: docker push sivatejanaidu78/businessnext-app:${{ steps.tag1.outputs.ImageTag }}
      
    - name: image size
      run: docker images

    - name: output image tag
      id: tag1
      run: echo "ImageTag=${{ github.sha::7 }}" >> "$GITHUB_OUTPUT"  
 


