name: pass outputs

on:
 push: 
  branches:
    - develop

jobs:
  passout:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.tag1.outputs.ImageTag }}
    steps:
    - name: image tag
      id: tag1
      run: echo "ImageTag=1.0.5" >> "$GITHUB_OUTPUT"

  accessoutputs:
    runs-on: ubuntu-latest
    needs: passout
    steps:
    - name: access outputs
      run: echo "Tag version of image was ${{needs.passout.outputs.output1}}"
      