name: Call a reusable workflow

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    
jobs:
  call-workflow:
    uses: ./.github/workflows/dockertest.yaml
    with:
      password: ${{ secrets.DOCKER_PASSWORD}} 
#    