name: Call a reusable workflow

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    
jobs:
  call-workflow:
    uses: ./.github/workflows/dockertest.yaml
    secrets:
      personal_access_token: ${{ secrets.token }}
#    